version: '3'
services:
  bus:
    image: chamalakiran/siribus:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: chamalakiran/siridth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: chamalakiran/sirirecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  train:
    image: chamalakiran/siritrain:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
