version: '3'
services:
  bus:
    image: chamalakiran/siribus:v1
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: chamalakiran/siridth:v1
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: chamalakiran/sirirecharge:v1
    ports:
      - "83:80"
    deploy:
      replicas: 3

  train:
    image: chamalakiran/siritrain:v1
    ports:
      - "94:80"
    deploy:
      replicas: 3
