version: '3'
services:
  bus:
    image: chamalakiran/movies:v1
    ports:
      - "85:80"
    deploy:
      replicas: 3

  dth:
    image: chamalakiran/dth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: chamalakiran/recharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  train:
    image: chamalakiran/train:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
