version: '3'
services:
  bus:
    image: chamalakiran/movies:v2
    ports:
      - "87:80"
    deploy:
      replicas: 3

  dth:
    image: chamalakiran/dth:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3

  recharge:
    image: chamalakiran/recharge:latest
    ports:
      - "89:80"
    deploy:
      replicas: 3

  train:
    image: chamalakiran/train:latest
    ports:
      - "90:80"
    deploy:
      replicas: 3
